source 'https://rubygems.org'

gem 'dashing-rails', '~> 2.4.0', :path => 'vendor/dashing-rails'
gem 'resque-scheduler', '~> 3.0.0'
gem 'puma'

gem 'twitter', '>= 5.0.0'
gem 'google-api-client'
gem 'mechanize'
gem 'unicode_utils'
gem 'i18n'
gem 'bootstrap-sass'
gem 'friendly_id'

gem 'rails', '4.1.4'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'simple_form', '~> 3.1.0.rc1', github: 'plataformatec/simple_form', branch: 'master'
