development:
  adapter: postgresql
  database: painel_social_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: painel_social_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: painel_social_production
  pool: 5
  timeout: 5000